name: Build Synclip Frontend Docker Image

on:
  push:
    branches:
      - master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            REACT_APP_BACKEND_API_ENDPOINT=https://synclip-api.tsingjyujing.com/
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tsingjyujing/synclip-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/synclip-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/synclip-frontend:buildcache,mode=max